# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Haroun H
tagline:          
description:      "My personal page."
url:              https://harounh.github.io
baseurl:          /
cv_address:       /public/pdfs/cv.pdf
things:           /things.md
author:
  name:           'Haroun Habeeb'
  url:            
  github:         https://github.com/harounh
paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/karloespiritu/blackdoc
